### ISSUE TITLE
Encryption/Decryption process not working on iOS

### ISSUE THREAD

**Issue by alexsalvetti** [evilsocket/arc#103]
Encryption/Decryption works perfectly on all PC! 👍 but on iOS, both on Safari:
`Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1` 
and Chrome:
`Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/63.0.3239.73 Mobile/14C92 Safari/602.1`

I get this error caught by the error handler:

![img_6373](https://user-images.githubusercontent.com/7389032/34114091-1152d8ac-e412-11e7-8a53-16d1df8394fd.PNG)

**Comment by evilsocket** [comment]
Due to [this](https://github.com/browscap/browscap/issues/1155) I can't see which iPhone, iOS and browser versions you are using, can you report that as well? The more details, the better :)

**Comment by evilsocket** [comment]
I'm testing this from an iPad Pro 10.5, updated both Safari and Chrome, I can not reproduce this issue.

**Comment by alexsalvetti** [comment]
I'm using an iPhone 6s with iOS 10.2, but I don't know how to determine which version of Safari I'm running.

**Comment by evilsocket** [comment]
Mmmm maybe outdated versions of iOS do not expose some WebCrypto objects (like the `TextEncoder`) to the browsers? I don't know honestly, will leave this open for now.

**Comment by alexsalvetti** [comment]
Maybe that could be a solution for legacy browser:
https://github.com/vibornoff/webcrypto-shim

**Comment by evilsocket** [comment]
Not sure if `TextEncoder` is part of WebCrypto, can't find references in that repo.

**Comment by evilsocket** [comment]
To be honest, I don't feel comfortable adding compatibility layers here and there considering we're talking about cryptographic functionalities, I can not guarantee for the security they actually offer (or compatibility with the native implementations), that is one of the main reasons why I moved this project from CryptoJS to the WebCrypto API.

Strong security requires modern tools, unfortunately Apple's policy is to not upgrade their stuff on older iOS versions, but that is not my responsibility.

I do not like it, but I can only mark this issue as closed.

**Comment by evilsocket** [comment]
Note: from [the next version](https://github.com/evilsocket/arc/commit/aaeb62a798d65f09732c7b641d579e2dfe5923bd) Arc will perform a deeper prerequisites checking process and alert the user if the browser is not fully compatible.

![banana](https://user-images.githubusercontent.com/86922/34121831-b4ab9a30-e42a-11e7-8264-12bebafed711.png)

**Comment by NuggTV** [comment]
@alexsalvetti I have the same Issue with me iPhone running iOS 10.x, with my i Pad running iOS 11.x everything works fine. @evilsocket was right, the problem is the outdated OS.

**Comment by alexsalvetti** [comment]
@NuggTV I know that but upgrading isn't worth the jailbreak 😂
