### ISSUE TITLE
Running arcd behind a TLS termination proxy

### ISSUE THREAD

**Issue by nabeelomer** [evilsocket/arc#111]
### Prerequisites

* [x] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [x] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [x] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

If I run `arcd` behind a TLS termination proxy (in my case Nginx) I get `http: TLS handshake error from 127.0.0.1:48160: tls: first record does not look like a TLS handshake`.

Is there a way to disable `arcd` TLS? If not, would you be open to adding one?

### Environment
`Linux ip-172-26-11-175 4.4.0-1044-aws #53-Ubuntu SMP Mon Dec 11 13:49:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
`arcd` needs to be run on TLS for a  [very specific reason](https://github.com/evilsocket/arc/issues/98), long story short, the browser only enable WebCrypto if the page is served from a secure origin ... if you can serve the html from nginx itself (with a valid certificate) that -might- work (if i'd implement the `--no-tls` feature), but why not just using it without nginx? You use custom certificates and the performances are already great.
