### ISSUE TITLE
Use Letsencrypt certificates 

### ISSUE THREAD

**Issue by jemacom** [evilsocket/arc#114]
### Description
I wonder if we can use Letsecrypt certificate instead of the current self signed one to see that fancy green lock on the browser :stuck_out_tongue_closed_eyes: . I found a package on [Gin-Gonic](https://github.com/gin-gonic/autotls) that we can use. But we need to solve out some issues before:
* We cannot generate certificate for localhost and static ip addresses. see [here](https://community.letsencrypt.org/t/certificate-for-static-ip/84/2?u=mholt).

* Look for a possibility to use virtual host names to solve the first issue. if yes how to create a unique one. 

Am not an expert on this but maybe we can learn from [Caddy](https://github.com/mholt/caddy/blob/master/caddytls/tls.go#L15) folks. 

I think am not the first one who thought about this but maybe we figured it out together.

**Expected behavior:** *What you expected to happen*
![screenshot from 2017-12-22 11-53-10](https://user-images.githubusercontent.com/6105096/34295705-02959368-e70f-11e7-88a1-223bf92e11d8.png)

**Actual behavior:** *What actually happened*
![screenshot from 2017-12-22 11-23-49](https://user-images.githubusercontent.com/6105096/34295707-06a5c43c-e70f-11e7-8cd8-42626ce7a06e.png)

--

**Comment by evilsocket** [comment]
Yes you can using the `certificate` and `key` configuration fields, it is not possible to generate them automatically as the procedure require a publicly available hostname, thing the software can not be aware of. So you can generate the cert yourself and use it via configuration.
