### ISSUE TITLE
Safari doesn't send Autohization header when creating stores

### ISSUE THREAD

**Issue by vasa-chi** [evilsocket/arc#120]
### Prerequisites

* [x] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [x] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [x] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

Safari doesn't send Autohization header when creating stores. Here's a copy of XHR request from Safari developer tools:
```
curl 'https://***/api/stores' \
-XPOST \
-H 'Referer: https://***/' \
-H 'Content-Type: application/json' \
-H 'Origin: https://***' \
-H 'Host: ***' \
-H 'Accept: application/json, text/javascript, */*; q=0.01' \
-H 'Connection: keep-alive' \
-H 'Accept-Language: ru' \
-H 'Accept-Encoding: br, gzip, deflate' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7' \
-H 'Content-Length: 16' \
-H 'X-Requested-With: XMLHttpRequest' \
--data-binary '{"Title":"test"}'
```

### Environment

Please provide:

* Contents of the json configuration file you are using (**remove the password hash before posting**).
```json
{
    "address": "0.0.0.0",
    "port": 8443,
    "secret": "***",
    "certificate": "***",
    "key": "***",
    "username": "***",
    "password": "***",
    "database": "~/db",
    "token_duration": 60,
    "compression": true,
    "scheduler": {
        "enabled": true,
        "period": 10,
        "reports": {
            "enabled": false,
            "rate_limit": 60,
            "filter": [ "login_ok", "login_ko", "token_ko", "update", "record_expired" ],
            "to": "youremail@gmail.com",
            "smtp":{
                "address": "smtp.gmail.com",
                "port": 587,
                "username": "youremail@gmail.com",
                "password": "your smtp password"
            },
            "pgp": {
                "enabled": true,
                "keys":{
                    "private": "~/server.private.key.asc",
                    "public": "~/my.public.key.asc"
                }
            }
        }
    },
    "backups": {
        "enabled": false,
        "period": 1800,
        "folder": "/some/backup/path/",
        "run": "scp arc-backup.tar user@backup-server:/media/arc_backup/"
    }
}
```

* Operating system and browser versions used as clients.
macOS 10.13.2, Safari 11.0.2 (13604.4.7.1.3)

* If possible, any javascript log on the browser developer console.
```
[Log] Creating store 'test' (api.js, line 155)
[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (stores, line 0)
```

* `uname -a` of the arcd server.
```
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
```

* Debug output while reproducing the issue ( `arcd --log-debug ...` ).
```
Jan 08 17:53:23 raspberrypi arcd[25433]: [2018-01-08 14:53:23]  INF  New event (Pool size is 20): token_ko{when:2018-01-08 17:53:23.961313253 +0300 MSK what:'Invalid token authentication.'}.
Jan 08 17:53:23 raspberrypi arcd[25433]: [2018-01-08 14:53:23]  WAR  <IP_ADDRESS> 'POST /api/stores' > [403] Forbidden
```

### Steps to Reproduce

1. Open arc in Safari
2. Click New store icon
3. Input name and press OK

**Expected behavior:** *What you expected to happen*
A new store is created

**Actual behavior:** *What actually happened*
No new store is created. An error popup with "Forbidden" message is shown.
API endpoint `POST /api/stores` returns 403 Forbidden.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by vasa-chi** [comment]
Same thing happens on current iOS on my iPhone and iPad :-(

**Comment by evilsocket** [comment]
ref https://twitter.com/evilsocket/status/961207503324418051

**Comment by evilsocket** [comment]
I can't reproduce it, on my iPad (latest iOS, latest Safari) it works:
![26151](https://user-images.githubusercontent.com/86922/35915765-5f40cd4e-0c08-11e8-874a-736dd2955e16.jpg)

**Comment by vasa-chi** [comment]
Sorry for late answer. 
I've tried on current version (1.1.11) and still have the same problem (on iPhone and mbp). 

I'll ask my friend with macbook to try to reproduce this bug, and get back to you as soon as I have more concrete data.

**Comment by clarkyjp** [comment]
Hi,

iOS 12.4.1 on iPhone X safari browser shows this behaviour only when trying create new stores. All other actions seem to work okay when a store is created on a windows machine.
