### ISSUE TITLE
Arc told me that i need to report this bug :)

### ISSUE THREAD

**Issue by elpagano3** [evilsocket/arc#124]
Arc version: 1.1.9
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0
Unhandled error on https://warriorcloud.pw:8888/js/libs/angular/angular.min.js:7:76

Error: [$rootScope:inprog] http://errors.angularjs.org/1.6.6/$rootScope/inprog?p0=%24apply

---------------------------------------------------------------------------------------------------------------------------------------
Please copy this message and report the bug here https://github.com/evilsocket/arc/issues/

Thanks!

**Comment by b0n3zx** [comment]
I got this same message but with my IP.  I logged out and used a different AES key to make a different store and naming it.
