### ISSUE TITLE
Support mail delivery by local means (mail/sendmail etc)

### ISSUE THREAD

**Issue by mulander** [evilsocket/arc#129]
### Prerequisites

* [x] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [x] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [x] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

I am hosting arc on our private server. This is the same machine self-hosting our email. Arc can notify it's user via email but expect SMTP configuration as follows:

```
            "smtp":{
                "address": "smtp.gmail.com",
                "port": 587,
                "username": "youremail@gmail.com",
                "password": "your smtp password"
            },
```

this is nice but on a server with a properly configured mail server, this is excessive and storing a password in clear text that should not be necessary.

The user running `arc` can send email by issuing commands like `$ echo test | mail -s test user@domain.tld` without providing any passwords and it would be very nice if `arcd` was able to do the same.

### Environment

Please provide:

* Contents of the json configuration file you are using (**remove the password hash before posting**). - not related.
* Operating system and browser versions used as clients. - OpenBSD/amd64 6.2 browser is not relevant
* If possible, any javascript log on the browser developer console. - not relevant
* `uname -a` of the arcd server.
```
$ uname -a
OpenBSD tintagel.pl 6.2 GENERIC#5 amd64
```
* Debug output while reproducing the issue ( `arcd --log-debug ...` ). - not relevant.

### Steps to Reproduce

1. Configure OpenSMTPD
2. Sacrifice a goat to MS & Google to have your mail delivered
3. Try to tell arc to use your existing setup

**Expected behavior:** *What you expected to happen*

I expect `arcd` to send email using the system available `mail` command.

**Actual behavior:** *What actually happened*

I have to set up smtp forcing arc to do a TCP/IP connection over TLS to localhost to send the same email instead of shelling out to `mail`.
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
> Sacrifice a goat to MS & Google to have your mail delivered

LOL

**Comment by evilsocket** [comment]
Mmmm I'm thinking about this ... given the email is PGP encrypted (not a single line), I wonder how to better handle this in the json configuration ...
