### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setStart' on 'Range': There is no child at offset 1

### ISSUE THREAD

**Issue by mulander** [evilsocket/arc#130]
### Prerequisites

* [x] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [x] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [x] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

Popup informing me to report this issue.

### Environment

Please provide:

* Contents of the json configuration file you are using (**remove the password hash before posting**). - not relevant
* Operating system and browser versions used as clients. - OpenBSD 6.2 and Chromium
* If possible, any javascript log on the browser developer console.
* `uname -a` of the arcd server. - OpenBSD tintagel.pl 6.2 GENERIC#5 amd64
* Debug output while reproducing the issue ( `arcd --log-debug ...` ). - not relevant

### Steps to Reproduce

1. Create a note with a HTML editor
2. Edit the note
3. mash ctrl-z like there's no tomorrow

**Expected behavior:** *What you expected to happen*
undoing changes

**Actual behavior:** *What actually happened*
a message popped up with the error.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

One more thing. The popup tells to 'copy' the text - it's not selectable so here's a screenshot.
![screenshot_2018-02-06_13-52-43](https://user-images.githubusercontent.com/107247/35860835-d28f47ee-0b45-11e8-87d2-e7476afebeaf.png)

**Comment by evilsocket** [comment]
ref https://github.com/summernote/summernote/issues/2017

**Comment by deepakkumarbarik** [comment]
Hi I am also getting same error. I am using the Angualr2 in my application please let me know how to how to fix this issue. Find the image below for more details.
![image](https://user-images.githubusercontent.com/3807461/66632673-a143d380-ec26-11e9-9e65-849a15579024.png)
