### ISSUE TITLE
HTML editor remembers the last saved content

### ISSUE THREAD

**Issue by mulander** [evilsocket/arc#131]
### Prerequisites

* [X] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [X] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [X] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

When creating a new HTML part it is instantiated pre-filled with content from previously saved HTML parts - even from other notes.

### Environment

Please provide:

* Contents of the json configuration file you are using (**remove the password hash before posting**). - not relevant, did on a fresh setup
* Operating system and browser versions used as clients. - OpenBSD 6.2 & current using Chromium
* If possible, any javascript log on the browser developer console.
```
Logging in ...
api.js:98 Logging in ...
api.js:108 Saving token to browser storage.
api.js:155 Creating store 'test'
2app.js:176 Loading passwords store ...
api.js:172 Selecting store '0'
api.js:138 Loading store-0 records ...
app.js:176 Adding secret ...
app.js:603 Building record with 1 entries.
record.js:43 Encrypting 99 bytes of record.
app.js:176 Loading passwords store ...
api.js:172 Selecting store '0'
api.js:138 Loading store-0 records ...
```

* `uname -a` of the arcd server. - OpenBSD tintagel.pl 6.2 GENERIC#5 amd64
* Debug output while reproducing the issue ( `arcd --log-debug ...` ).

### Steps to Reproduce

1. create a new note
2. add a HTML widget
3. type something in it
4. save the note
5. create a new note
6. add a HTML widget

**Expected behavior:** *What you expected to happen*
I expect a newly created HTML widget to always be empty.

**Actual behavior:** *What actually happened*
It's pre-filled with data from step 3.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
This is a very bad bug, caused [by this operation](https://github.com/evilsocket/arc/blob/master/arc/js/entries.js#L125) not to working as expected, basically the object itself is cloned but its attributes remain as references, meaning all the components of the same type on a single page share this problem .... trying to find a way to better clone these objects :)

**Comment by evilsocket** [comment]
KISS :)
