### ISSUE TITLE
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.

### ISSUE THREAD

**Issue by mulander** [evilsocket/arc#132]
![screenshot_2018-02-06_14-59-13](https://user-images.githubusercontent.com/107247/35863867-54607590-0b50-11e8-9bfa-c142688d6b54.png)
### Prerequisites

* [x] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [x] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [x] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

Pop up informing me to report the above error.

### Environment

Please provide:

* Contents of the json configuration file you are using (**remove the password hash before posting**). - not relevant
* Operating system and browser versions used as clients. - OpenBSD 6.2 & Chromium
* If possible, any javascript log on the browser developer console. - that's gone, sorry
* `uname -a` of the arcd server. - OpenBSD tintagel.pl 6.2 GENERIC#5 amd64
* Debug output while reproducing the issue ( `arcd --log-debug ...` ). - not relevant

### Steps to Reproduce

This is how wife explained the steps that lead to the bug.

1. Ctrl-a by accident selected all elements on the page (outside the editor)
2. Tried to click 'not on the editor' to deselect
3. She said when she moved the mouse the selected area was 'dragged with the mouse'
4. Clicking in that state caused the popup

**Expected behavior:** *What you expected to happen*
No popups :)

**Actual behavior:** *What actually happened*
Popup, then all elements on the page removed after the popup was dismissed.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
i'm sorry but whit this type of inaccurate explaination i wasn't able to reproduce the issue, I need to know exactly what "page" she is using, the contents of such page, etc ... please try to reproduce it yourself and post **exact** steps.

**Comment by mulander** [comment]
Not a problem, it was a one off in this case. I still want to post every issue that results in the pop-up alert in case she hits it again. I will try to reproduce this one myself and condense it down to better steps.

Side note: she loves arc so far :)

**Comment by evilsocket** [comment]
And that's awesome, you spotted [a very bad bug](https://github.com/evilsocket/arc/issues/131) (not just related to that component, it's way worse than it seems, trying to find a way to fix it now :D)

**Comment by mulander** [comment]
I can cause multiple variations of this issue.

![2018-02-07-154024_428x346_scrot](https://user-images.githubusercontent.com/107247/35922205-42a10d10-0c1d-11e8-8a29-6d6cb496c3d4.png)
![2018-02-07-154058_1326x484_scrot](https://user-images.githubusercontent.com/107247/35922235-53727b4c-0c1d-11e8-9607-489279edc866.png)

Steps I take to lead to such a broken state:
1. Create a new note
2. Create a new html editor
3. Select the whole page (ctrl-a when focus is outside the editor)
4. Drag and drop the selection on the editor (you get a hint you can drop image or text there).

I was not able to re-create the original traceback though.
