### ISSUE TITLE
cannot find package "github.com/gin-gonic/gin/json"

### ISSUE THREAD

**Issue by rytma** [evilsocket/arc#143]
### Prerequisites

* [x] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [x] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [x] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

The make file return this error during compilation:

```
controllers/main.go:31:2: cannot find package "github.com/gin-gonic/gin/json" in any of:
	/usr/lib/go/src/github.com/gin-gonic/gin/json (from $GOROOT)
	/home/rytma/go/src/github.com/gin-gonic/gin/json (from $GOPATH)
make: *** [Makefile:18: vet] Error 1
```

### Steps to Reproduce

1. *git clone https://github.com/evilsocket/arc $GOPATH/src/github.com/evilsocket/arc*
2. *cd $GOPATH/src/github.com/evilsocket/arc/arcd*
3. *make*

**Actual behavior:** *What actually happened*

it doesn't found the gin/json library, but a simple solution is to comment the line (controllers/main.go:31:2:):
`import "github.com/gin-gonic/gin/json"`
and add the following line:
`import "encoding/json"`

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by mulander** [comment]
It seems that the gin-gonic authors [decided](https://github.com/gin-gonic/gin/pull/1504) to make the json package `internal`. I tried using it by altering the import path `"github.com/gin-gonic/gin/internal/json"` but that fails during compilation with:

```
tintagel$ make
controllers/main.go:31:2: use of internal package github.com/gin-gonic/gin/internal/json not allowed
*** Error 1 in /home/mulander/arctest/src/github.com/evilsocket/arc/arcd (Makefile:18 'vet': @go vet .)
```

I ended up using the workaround provided by @rytma for my immediate needs.

**Comment by rytma** [comment]
because you can't import internal package on golang from an external folder. To do that you probably need to rename the folder and all the relative code, that's why I opted to change only the import

**Comment by mulander** [comment]
@rytma You could open up a pull request with the change. I saw you close the ticket and just wanted to make sure you're not mistaking me for the project author. I just happened to hit the same issue and used your fix for my local copy - I have no commit permission for this repository.

**Comment by hbqhzx** [comment]
obviously，The package has no json in your version. If you want to continue to use it, you need to back off the version to 1.3.0，just run `go get github.com/gin-gonic/gin@v1.3.0`
