### ISSUE TITLE
v1.3.2 release binaries for OpenBSD are incompatible with the 6.4 release

### ISSUE THREAD

**Issue by mulander** [evilsocket/arc#144]
### Prerequisites

* [X] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [X] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [X] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

The latest release binary works correctly on OpenBSD 6.3
The same binary fails on OpenBSD 6.4 with a segmentation fault and the following
trap:
![2018-12-29-191708_753x144_scrot](https://user-images.githubusercontent.com/107247/50541596-5da53f00-0ba9-11e9-8f50-19313ead8c62.png)

**This is expected and not a bug of arc itself.** This is the result of no guarantees of long term ABI stability on OpenBSD. Officially the Go compiler supports the last two releases:

> Longterm support
> Go aims to support the two most recent OpenBSD releases, because OpenBSD officially supports only the two most recent releases, and makes a best-effort attempt to maintain ABI support in consecutive releases.

source: https://github.com/golang/go/wiki/OpenBSD#longterm-support

However, at the time the 1.3.2 release of arc was compiled OpenBSD 6.3 was the main release so the binary fails now.

I have recompiled the code on the same machine instead of using the release binary and it works.

### Solution

Can you recompile and re-upload the openbsd build artifacts or upload them as new files with 6.4 present in the name to indicate they work on 6.4?

Judging by the excerpt from Go docs the new binary should also work on 6.3 but I don't have a machine with 6.3 around.

### Environment

OpenBSD 6.4 amd64

### Steps to Reproduce

1. Install OpenBSD 6.4
2. Download arc_1.3.2_openbsd_amd64.tar.gz
3. Unpack and execute `arcd`

**Expected behavior:** *What you expected to happen*

```
tintagel$ ./arcd
[2018-12-29 18:48:33]  INF  arcd v1.3.2 (openbsd amd64) is starting ...
```
**Actual behavior:** *What actually happened*

```
tintagel$ ./arcd
Segmentation fault (core dumped) 
```
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
can you check if the new release is working?

**Comment by mulander** [comment]
Hi, sorry for the long delay.

I just tested release v1.3.4 against stock OpenBSD 6.6. Works out of the box.

I'm closing the issue, thanks! :)
