### ISSUE TITLE
Error while decrypting record data

### ISSUE THREAD

**Issue by alexsalvetti** [evilsocket/arc#146]
### Prerequisites

* [x] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [x] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [x] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

Error while decrypting record data. If I create notes from different devices, the notes can be opened only with the device they've been created with.   

### Environment

Please provide:

* Contents of the json configuration file I'm using:
`{
    "address": "0.0.0.0",
    "port": 8443,
    "secret": "secret",
    "certificate": "~/arcd-certificate.pem",
    "key": "~/arcd-key.pem",
    "username": "user",
    "password": "password",
    "database": "~/db",
    "token_duration": 60,
    "compression": true,
    "scheduler": {
        "enabled": true,
        "period": 10,
        "reports": {
            "enabled": false,
            "rate_limit": 60,
            "filter": [ "login_ok", "login_ko", "token_ko", "update", "record_expired" ],
            "to": "youremail@gmail.com",
            "smtp":{
                "address": "smtp.gmail.com",
                "port": 587,
                "username": "youremail@gmail.com",
                "password": "your smtp password"
            },
            "pgp": {
                "enabled": true,
                "keys":{
                    "private": "~/server.private.key.asc",
                    "public": "~/my.public.key.asc"
                }
            }
        }
    },
    "backups": {
        "enabled": false,
        "period": 1800,
        "folder": "/some/backup/path/",
        "run": "scp arc-backup.tar user@backup-server:/media/arc_backup/"
    }
}
`

* Operating system and browser versions used as clients:
`Windows 10 - Chrome Version 74.0.3729.131 (Official Build) (64-bit)`
`Safari iOS 11.3.1 and iOS 12.1`
* `uname -a` of the arcd server:
`Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux`

### Steps to Reproduce

1. *Create a note from Windows on Chrome and save it*
2. *Try to reopen the note form Chrome and it opens*
3. *Log in with an iPhone on arc*
4. *Try to reopen the note created on the Windows computer an I get the message `Error while decrypting record data`*
5. *If I create a note on the iPhone then I can reopen it from different iPhones with different iOS versions but not from the Windows computer*

**Expected behavior:** *Open the notes from different devices*

**Actual behavior:** *Can open the notes only if created by similar devices*

**Screenshot:** *Note "Test1" created on the iPhone cannot be open, note "Test2" created on the computer can be open:*
![image](https://user-images.githubusercontent.com/7389032/57584276-7a4b6f00-74d9-11e9-8fba-97124caa6c2e.png)

**Comment by evilsocket** [comment]
are you sure you're using the same encryption key? i do this regularly (creating stuff from different devices with the same key) and it works

**Comment by alexsalvetti** [comment]
You right, I rechecked and I copied a wrong encryption key when I created those notes. Sorry for the stupid issue.
