### ISSUE TITLE
Some error in the README file

### ISSUE THREAD

**Issue by m0rp30** [evilsocket/arc#153]
### Prerequisites

* [X] Did you read the [README](https://github.com/evilsocket/arc/blob/master/README.md)?
* [X] Are you running the [latest version](https://github.com/evilsocket/arc/releases/latest)?
* [X] Did you search [other issues](https://github.com/evilsocket/arc/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported?

### Description

At the paragraph **USAGE**, the correct command should be `go install github.com/evilsocket/arc/cmd/arc@latest` because the command `go get ...` is deprecated

A few, little, issue at the command `arc ...` for missing usage of **./** after **arc** command and, in my case, if i use `./arc -config config.json -app ./arc` or `... -app arc` i get an error like `flag provided but not defined: -app...`

### Environment

Please provide:

* Contents of the json configuration file you are using (**remove the password hash before posting**).
```
{
    "address": "127.0.0.1",
    "port": 8443,
    "secret": "DELETED",
    "certificate": "~/arc-certificate.pem",
    "key": "~/arc-key.pem",
    "username": "DELETED",
    "password": "DELETED",
    "database": "~/db",
    "token_duration": 60,
    "compression": true,
    "scheduler": {
        "enabled": true,
        "period": 10,
        "reports": {
            "enabled": false,
            "rate_limit": 60,
            "filter": [ "login_ok", "login_ko", "token_ko", "update", "record_expired" ],
            "to": "youremail@gmail.com",
            "smtp":{
                "address": "smtp.gmail.com",
                "port": 587,
                "username": "youremail@gmail.com",
                "password": "your smtp password"
            },
            "pgp": {
                "enabled": true,
                "keys":{
                    "private": "~/server.private.key.asc",
                    "public": "~/my.public.key.asc"
                }
            }
        }
    },
    "backups": {
        "enabled": false,
        "period": 1800,
        "folder": "/some/backup/path/",
        "run": "scp arc-backup.tar user@backup-server:/media/arc_backup/"
    }
}

```
* Operating system and browser versions used as clients.
EndeavourOS
* `uname -a` of the arc server.
`Linux ragnarock 6.3.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 15:12:57 +0000 x86_64 GNU/Linux`

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by rossajmcd** [comment]
Hi @m0rp30 - I saw your update on issues and a wondering did you get it running? I'm currently seeing some of the same issues and the service will not start - it is failing with the message: '!!! No PEM block found.'. I'm running it on a Pi Zero W.
