### ISSUE TITLE
Find a decent bootstrap theme.

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/arc#51]
Find and use a decent bootstrap theme.

**Comment by jhonnymoreira** [comment]
Is it really needed a bootstrap theme? If not, would you accept a handmade theme?

I can help with this issue in both ways.

**Comment by evilsocket** [comment]
Not necessarily, the main things is: I suck with CSS and HTML and this project is so nice it deserves a cool UI imho :P Any help is appreciated, before sending a PR or anything maybe send a few screenshots of mockups or whatever so we can discuss it.

**Comment by jhonnymoreira** [comment]
It really deserves a nice UI hahahahaha

Do you have any UI references that I could use?

**Comment by evilsocket** [comment]
to be honest i'd love to keep it clean, simple and minimal as it is, github UI is a nice example of that, but i'm 100% open to new ideas :D

**Comment by jhonnymoreira** [comment]
Alright. I'm at work right now, but as soon as I'm home, I'll try to brainstorm a few things so we can discuss!

Thanks!

**Comment by evilsocket** [comment]
Thank you for your help ^_^ looking forward to it.

**Comment by jhonnymoreira** [comment]
Hey @evilsocket sorry for my disappearance, I'm having no time. I'll be free Friday (15/12)!

**Comment by TheMcSebi** [comment]
http://brobin.github.io/hacker-bootstrap/
