### ISSUE TITLE
Write server unit tests.

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/arc#61]
The `arcd` server should be fully covered by tests.

**Comment by Bedotech** [comment]
i want start to work on this issue, i have no experience in write Golang test, there are some project that i can take as case study for reproduce here the same pattern? i can take the (git-gonic)[https://github.com/gin-gonic/gin]?

**Comment by evilsocket** [comment]
gin tonic looks like a good example :)

**Comment by jemacom** [comment]
I'm trying to write some tests for ```utils``` package. But I got weird results from ```FormatBytes``` function. 
For example: 
```
42 MB => 44040192
42000000 => 40,05 MB
```  
Although the function output is
```
44040192 => 44 MB
42000000 => 42 MB
```

Check more examples [here](https://play.golang.org/p/sa5vc5FhI8b)

I see that the function is mainly used to log messages about file sizes. I wanna know if it's intentionally written like this or it needs some fixes?
 
Cheers !

**Comment by evilsocket** [comment]
iirc that function was copy/pasted from somewhere, as you mentioned it is only used for logging so to be 100% honest i did not pay much attention to it :P fixes and in general PRs are **more** than welcome :D

**Comment by evilsocket** [comment]
(Feel free also to fill a bug about that function of course.)
