### ISSUE TITLE
Replace CryptoJS with WebCrypto

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/arc#72]
WebCrypto is [waaaay faster](https://medium.com/@encryb/comparing-performance-of-javascript-cryptography-libraries-42fb138116f3) and using it will reduce the JS data we load, execute, etc.

It's just a matter of reimplementing the `AESEncrypt` and `AESDecrypt` functions in the [arc/js/encryption.js](https://github.com/evilsocket/arc/blob/master/arc/js/encryption.js) file.

**Comment by raffaeleflorio** [comment]
I can work on this issue! :+1:

**Comment by evilsocket** [comment]
Looking forward for your PR :D thank you <3

**Comment by raffaeleflorio** [comment]
It's a pleasure, glad to help!

After this enhancement there could be another improvement, because the async nature of WebCrypto. The encryption progress could be on the right of the record, where now there is the record status. In this way multiple records could be encrypted simultaneously. I think that the back-end permit this feature.

**Comment by evilsocket** [comment]
let start with small steps by replacing cryptojs, then we will see ^_^

**Comment by raffaeleflorio** [comment]
Seems done! I'll do the commit soon. :smile:

**Comment by raffaeleflorio** [comment]
I confirm, It's done. However previous encrypted record with CryptoJS cannot be decrypted with WebCrypto.

**Comment by raffaeleflorio** [comment]
CryptoJS removed definitely. Password generator is using WebCrypto, too. :D

**Comment by evilsocket** [comment]
> However previous encrypted record with CryptoJS cannot be decrypted with WebCrypto.

Why? If the format is the same, it should be backwards compatible.

**Comment by raffaeleflorio** [comment]
Yeah it seems strange to me too.. The format is the same (hex + hex + base64). Nonetheless WebCrypto is unable to decrypt.

**Comment by evilsocket** [comment]
Mmmm not a big deal since I did not release 1.0.0 yet :) Why don't you send the PR so I can test a bit? :P

**Comment by raffaeleflorio** [comment]
> Mmmm not a big deal since I did not release 1.0.0 yet :)
 :+1:

> Why don't you send the PR so I can test a bit? :P
Done! :D

**Comment by evilsocket** [comment]
I had to revert it, indentation is broken pretty much everywhere and new code has mistakes, for example a decryption error is just logged.

**Comment by raffaeleflorio** [comment]
Does the decryption error is related to the CryptoJS encrypted records?

**Comment by evilsocket** [comment]
I'm talking about this, if this happens, the UI is not updated with the error because `setError` is not defined for `that` ( it used to be the `scope` object I guess ... )

https://github.com/raffaeleflorio/arc/blob/webcrypto/arc/js/record.js#L64

**Comment by evilsocket** [comment]
I believe the `record.HasError()` condition in the callback is never executed because of the error

**Comment by raffaeleflorio** [comment]
> I had to revert it, indentation is broken pretty much everywhere

Did you use spaces?

> I believe the record.HasError() condition in the callback is never executed because of the error

Yeah, the bug is here. 👍

**Comment by raffaeleflorio** [comment]
Fixed, however WebCrypto error message aren't informative..

**Comment by evilsocket** [comment]
I'm testing your code right now, i'll merge as soon as I'm 100% sure it works as expected, meanwhile, **thank you <3**

**Comment by evilsocket** [comment]
Eventually I used your code and some examples on the web to reimplement it myself in a cleaner and faster way ^_^
