### ISSUE TITLE
cant compile arcd

### ISSUE THREAD

**Issue by MajorCrazed** [evilsocket/arc#79]
main.go:17:2: cannot find package "github.com/evilsocket/arc/arcd/app" in any of:
	/usr/share/go-1.7/src/github.com/evilsocket/arc/arcd/app (from $GOROOT)
	/home/pi/arc/arcd/_vendor/src/github.com/evilsocket/arc/arcd/app (from $GOPATH)
	/home/pi/go/src/github.com/evilsocket/arc/arcd/app
main.go:18:2: cannot find package "github.com/evilsocket/arc/arcd/config" in any of:
	/usr/share/go-1.7/src/github.com/evilsocket/arc/arcd/config (from $GOROOT)
	/home/pi/arc/arcd/_vendor/src/github.com/evilsocket/arc/arcd/config (from $GOPATH)
	/home/pi/go/src/github.com/evilsocket/arc/arcd/config
main.go:19:2: cannot find package "github.com/evilsocket/arc/arcd/controllers" in any of:
	/usr/share/go-1.7/src/github.com/evilsocket/arc/arcd/controllers (from $GOROOT)
	/home/pi/arc/arcd/_vendor/src/github.com/evilsocket/arc/arcd/controllers (from $GOPATH)
	/home/pi/go/src/github.com/evilsocket/arc/arcd/controllers
main.go:20:2: cannot find package "github.com/evilsocket/arc/arcd/log" in any of:
	/usr/share/go-1.7/src/github.com/evilsocket/arc/arcd/log (from $GOROOT)
	/home/pi/arc/arcd/_vendor/src/github.com/evilsocket/arc/arcd/log (from $GOPATH)
	/home/pi/go/src/github.com/evilsocket/arc/arcd/log
main.go:21:2: cannot find package "github.com/evilsocket/arc/arcd/middlewares" in any of:
	/usr/share/go-1.7/src/github.com/evilsocket/arc/arcd/middlewares (from $GOROOT)
	/home/pi/arc/arcd/_vendor/src/github.com/evilsocket/arc/arcd/middlewares (from $GOPATH)
	/home/pi/go/src/github.com/evilsocket/arc/arcd/middlewares
main.go:22:2: cannot find package "github.com/evilsocket/arc/arcd/models" in any of:
	/usr/share/go-1.7/src/github.com/evilsocket/arc/arcd/models (from $GOROOT)
	/home/pi/arc/arcd/_vendor/src/github.com/evilsocket/arc/arcd/models (from $GOPATH)
	/home/pi/go/src/github.com/evilsocket/arc/arcd/models
main.go:23:2: cannot find package "github.com/evilsocket/arc/arcd/utils" in any of:
	/usr/share/go-1.7/src/github.com/evilsocket/arc/arcd/utils (from $GOROOT)
	/home/pi/arc/arcd/_vendor/src/github.com/evilsocket/arc/arcd/utils (from $GOPATH)
	/home/pi/go/src/github.com/evilsocket/arc/arcd/utils
Makefile:21: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by evilsocket** [comment]
What's the content of your `$GOPATH` ? Did you configure it correctly?

**Comment by MajorCrazed** [comment]
pi@raspberrypi:~ $ go env
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_arm"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build871180188=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

**Comment by MajorCrazed** [comment]
GOPATH is set to /home/pi/go so i think it is correctly set

**Comment by evilsocket** [comment]
And where did you clone the repo? It should be inside `/home/pi/go/src/github.com/evilsocket/arc`

**Comment by jemacom** [comment]
@evilsocket I think we need to mention this in the installation instruction. 
```
$mkdir -p $GOPATH/github.com/evilsocket
$git clone https://github.com/evilsocket/arc  $GOPATH/github.com/evilsocket/arc
$cd $GOPATH/github.com/evilsocket/arc/arcd
```
That way It won't confusions around this ;)

I can open a PR for this if you want.

**Comment by v-po** [comment]
You can also just make symbolic link: 

`ln -s /path/to/arc/arcd $GOPATH/src/github.com/evilsocket/arc/`

**Comment by evilsocket** [comment]
I'm closing this as when 1.0.0 will be out (very soon) binary releases will be provided and code compilation instructions updated.
