### ISSUE TITLE
Markdown rendering script stucks

### ISSUE THREAD

**Issue by raffaeleflorio** [evilsocket/arc#80]
When Markdown is being rendered, the application stucks. On my PC this is caused when the text is, approximately, bigger than 34KB.
Other types of rendering doesn't cause stuck.

**Comment by evilsocket** [comment]
On which browser and os?

**Comment by evilsocket** [comment]
This looks browser or os specific, I'm not able to reproduce the issue with about 100Kb of markdown on latest Firefox and Chromium on Ubuntu.

**Comment by raffaeleflorio** [comment]
I tried with Firefox 57 on Fedora.

**Comment by evilsocket** [comment]
It looks like a very os-browser-version specific issue, I will close this for now unless someone else will report the same kind of behaviour in newer releases.
