### ISSUE TITLE
Problem renaming or editing record

### ISSUE THREAD

**Issue by Giorgiofox** [evilsocket/arc#97]
If I try to rename a record, I can't use all letters used in keyboard shortcut, so for example, is impossible to rename a record with "Password", because when I type "d" it ask me "Are you sure" because "d" is shortcut for delete. 

The same happens also with a record in a Text field.. very annoying. 

I'm using a Raspberry 3 with Stretch lite, ARC 1.0.6 and Safari and Firefox on a Mac. 

Thank you!

**Comment by evilsocket** [comment]
This bug was fixed in theory, did you make sure to uncache all the javascript on your browser before reloading the app?

**Comment by Giorgiofox** [comment]
Problem solved cleaning cache. Thank you
