### ISSUE TITLE
Uncaught TypeError: Cannot read property 'importKey' of undefined

### ISSUE THREAD

**Issue by alexsalvetti** [evilsocket/arc#98]
Hi, I've some problems with Encryption/Decryption of records on Linux with Chrome Version 62.0.3202.62 but Firefox works great! On iOS neither Safari or Chrome are working. When I hit save it stuck on the "Encrypting record" pop-up.

**Comment by NuggTV** [comment]
I have the same Problem. Arc is running on my Raspberry Pi. Accessing from a Mac with Crome gives me the same error. With Safari everything works fine.

**Comment by evilsocket** [comment]
"Encrypting record" is not an error, it means that the app is **encrypting the record** ... webcrypto can have different speeds depending on the browser you're using, what is the size of the record you're encrypting? Does it contain any file? Any javascript errors on the developer console?

**Comment by NuggTV** [comment]
The Size of the record is not the problem. I have tried it with only one line of text with the same result. Also i can't decrypt files via chrome. If i crate a test file with Safari and then change the browser to Chrome decrypting is also not possible. Stuck at Decrypting Data at 100%. I have checked the console with gives me the following errors:

Logging in ...
api.js:98 Logging in ...
2app.js:182 Loading passwords store ...
api.js:172 Selecting store '0'
api.js:138 Loading store-0 records ...
app.js:676 Loading record 1
app.js:244 LOADER> Buffering data ...
app.js:244 LOADER> Decrypting data ...
record.js:64 Decrypting 144 bytes of data.
encryption.js:62 Uncaught TypeError: Cannot read property 'importKey' of undefined
    at PBKDF2 (encryption.js:62)
    at AESDecrypt (encryption.js:95)
    at Record.Decrypt (record.js:65)
    at app.js:686

I hope that can help you reproduce the problem. Thanks for your great work

**Comment by evilsocket** [comment]
Oh now I see .... @NuggTV would you do something for me? In the developer console, execute this and paste the output please:

```javascript
console.log( "window.crypto", window.crypto );
console.log( "window.crypto.subtle", window.crypto.subtle );
console.log( "window.crypto.webkitSubtle", window.crypto.webkitSubtle );```

**Comment by NuggTV** [comment]
Sure, i hope i did it right. I don't have much experience with the console.

![console](https://user-images.githubusercontent.com/34648798/34107034-ef1f59de-e3fa-11e7-8e5a-e7941e9c100b.png)

**Comment by evilsocket** [comment]
perfect! ok now i need for figure out how to solve it :D stay tuned ;)

**Comment by evilsocket** [comment]
For reference, this behaviour seems to be intentional, cryptographic functionalities are disabled if the page is served from an "insecure origin" ( [specs here](https://github.com/w3c/webcrypto/issues/28) ) ... looking how to fix this.

**Comment by alexsalvetti** [comment]
I found that:

Which origins are "secure"?
Secure origins are those that match at least one of the following (scheme, host, port) patterns:

(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
(chrome-extension, *, —)

That is, secure origins are those that load resources either from the local machine (necessarily trusted) or over the network from a cryptographically-authenticated server.
See Prefer Secure Origins For Powerful New Features for more details: http://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

**Comment by evilsocket** [comment]
Reproduced on Linux too ( Chromium ).

![bug](https://user-images.githubusercontent.com/86922/34107495-b9e924be-e3fc-11e7-9d6a-df7d86a96d73.png)

**Comment by alexsalvetti** [comment]
Now it's perfectly working on all my PC! :+1: but on iOS, both on Safari and Chrome, I get now this error cauth by the error handler:
![img_6374](https://user-images.githubusercontent.com/7389032/34112569-4592d1d0-e40d-11e7-803b-808109aefad3.PNG)

BTW great work! ;)

**Comment by evilsocket** [comment]
Can you report that message in a new issue and also the iOS and browser versions you are using?
